// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBGFNOveEUP-qeq5F-ge5dNZSd4cgdSpw',
    appId: '1:650912791517:web:0989b19302afbdaddb1434',
    messagingSenderId: '650912791517',
    projectId: 'mobilekb-28e7c',
    authDomain: 'mobilekb-28e7c.firebaseapp.com',
    storageBucket: 'mobilekb-28e7c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_B6dFfSgd74yOh3UGsmKcZvfgSN7XoB8',
    appId: '1:352389574731:android:4960a9a090136301975dce',
    messagingSenderId: '352389574731',
    projectId: 'kbmobile-7d5ed',
    storageBucket: 'kbmobile-7d5ed.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBilCLjZHo_tZasUlBw4h2QNGJ2GheZNts',
    appId: '1:352389574731:ios:1b756d620c2d04b7975dce',
    messagingSenderId: '352389574731',
    projectId: 'kbmobile-7d5ed',
    storageBucket: 'kbmobile-7d5ed.firebasestorage.app',
    iosBundleId: 'com.example.imageapp',
  );

}